name: DreamAllInOne
main: at.lucas.dream.main.Main
version: 0.1
api-version: 1.16
commands:
  settings:
    description: Opens the settingsmenu
  dstart:
    description: Starts all selected Challengesx
  dstop:
    description: Stops all Challenges imediately